### ISSUE TITLE
Epic 1 - User Story 1: Set up basic Express application.

### ISSUE THREAD

**Issue by Greedent82** [SchoolOfCode/bc17-w4d2-project-smiths-co#1]
```[tasklist]
### Tasks
- [x] Clone repositry
- [x] Navigate to project folder
- [x] npm init -y
- [x] type module in package
- [x] npm install express
- [x] creates app.js file
- [x] import and set up express server
- [x] set up basic get route to respond with hello world
- [x] test out in postman
- [ ] update readme to detail how to install and run
```
