### ISSUE TITLE
Epic 1 - User Story 2: Add basic security standards using Helmet 

### ISSUE THREAD

**Issue by Greedent82** [SchoolOfCode/bc17-w4d2-project-smiths-co#2]
```[tasklist]
### Tasks
- [x] npm install helmet
- [x] import helmet into ```app.js```
- [x] use helmet middleware utilising ```app.use```
```
