### ISSUE TITLE
Epic 2 - User Story 1: Implement functionality to get all activities for a particular user

### ISSUE THREAD

**Issue by ianbsmythe** [SchoolOfCode/bc17-w4d2-project-smiths-co#3]
```[tasklist]
### Tasks
- [x] Create a .json with relevant data
- [x] construct the API with object with an internal array
- [x] Import .json data into app.js
- [x] Create Express GET request handler
- [x] create a variable to capture path paramater from the GET request URL
- [x] create blank array so we can shove multiple objects into the array
- [x] Iterate through the array and put objects (into the blank array) with a matching id
- [x] make a response code status
- [x] Testing in browser/postman
```
