### ISSUE TITLE
Epic 2 - User Story 2: Implement functionality to POST a new activity.

### ISSUE THREAD

**Issue by Greedent82** [SchoolOfCode/bc17-w4d2-project-smiths-co#4]
```[tasklist]
### Tasks
- [x] `app.post` request handler
- [x] take post request from client `req.body...`
- [x] update activities array with new activity object (spread operator) + push
- [x] check data sent is valid
- [x] implement `date.now` and UUID
- [x] Add a new object to our current in memory activities array
- [x] response contains data or error
```
